---
- name: Ensure supervisor is at the latest version
  apt:
    pkg: supervisor
    state: latest
- name: Remove supervisor lock
  file: 
    path: /run/supervisord.lock
    state: absent
- name: Ensure specific supervisor conf is here
  file:
    path: /etc/supervisor/conf.d
    state: directory
- name: Ensure supervisor is running
  service: 
    name: supervisor
    state: started
- name: Copy default Ghost configuration
  copy:
    src: ghost.conf.default
    dest: /etc/supervisor/conf.d/ghost.conf.default