---
- name: Copy a correct .bash_profile
  copy:
    src: bash_profile
    dest: "/home/{{user}}/.bash_profile"
- name: Copy a correct .vim_rc
  copy:
    src: vimrc
    dest: "/home/{{user}}/.vimrc"
